;;;; c-api.lisp --- CFFI bindings generated from xgboost/c_api.h.
;;;;
;;;; Generated by tools/regen.lisp. Do not edit by hand.

(in-package #:cl-gbdt.xgboost.ffi)

(cffi:defcfun ("XGBoostVersion" xg-boost-version) :void
  (major :pointer)
  (minor :pointer)
  (patch :pointer))

(cffi:defcfun ("XGBuildInfo" xg-build-info) :int
  (out :pointer))

(cffi:defcfun ("XGBGetLastError" xgb-get-last-error) :pointer)

(cffi:defcfun ("XGBRegisterLogCallback" xgb-register-log-callback) :int
  (callback :pointer))

(cffi:defcfun ("XGBSetGlobalConfig" xgb-set-global-config) :int
  (config :pointer))

(cffi:defcfun ("XGBGetGlobalConfig" xgb-get-global-config) :int
  (out-config :pointer))

(cffi:defcfun ("XGDMatrixCreateFromFile" xgd-matrix-create-from-file) :int
  (fname :pointer)
  (silent :int)
  (out :pointer))

(cffi:defcfun ("XGDMatrixCreateFromURI" xgd-matrix-create-from-uri) :int
  (config :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixCreateFromColumnar" xgd-matrix-create-from-columnar) :int
  (data :pointer)
  (config :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixCreateFromCSR" xgd-matrix-create-from-csr) :int
  (indptr :pointer)
  (indices :pointer)
  (data :pointer)
  (ncol :uint64)
  (config :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixCreateFromDense" xgd-matrix-create-from-dense) :int
  (data :pointer)
  (config :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixCreateFromCSC" xgd-matrix-create-from-csc) :int
  (indptr :pointer)
  (indices :pointer)
  (data :pointer)
  (nrow :uint64)
  (config :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixCreateFromMat" xgd-matrix-create-from-mat) :int
  (data :pointer)
  (nrow :uint64)
  (ncol :uint64)
  (missing :float)
  (out :pointer))

(cffi:defcfun ("XGDMatrixCreateFromMat_omp" xgd-matrix-create-from-mat-omp) :int
  (data :pointer)
  (nrow :uint64)
  (ncol :uint64)
  (missing :float)
  (out :pointer)
  (nthread :int))

(cffi:defcfun ("XGDMatrixCreateFromCudaColumnar" xgd-matrix-create-from-cuda-columnar) :int
  (data :pointer)
  (config :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixCreateFromCudaArrayInterface" xgd-matrix-create-from-cuda-array-interface) :int
  (data :pointer)
  (config :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixCreateFromDataIter" xgd-matrix-create-from-data-iter) :int
  (data-handle :pointer)
  (callback :pointer)
  (cache-info :pointer)
  (missing :float)
  (out :pointer))

(cffi:defcfun ("XGDMatrixCreateFromCallback" xgd-matrix-create-from-callback) :int
  (iter :pointer)
  (proxy :pointer)
  (reset :pointer)
  (next :pointer)
  (config :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixSliceDMatrix" xgd-matrix-slice-d-matrix) :int
  (handle :pointer)
  (idxset :pointer)
  (len :uint64)
  (out :pointer))

(cffi:defcfun ("XGDMatrixSliceDMatrixEx" xgd-matrix-slice-d-matrix-ex) :int
  (handle :pointer)
  (idxset :pointer)
  (len :uint64)
  (out :pointer)
  (allow-groups :int))

(cffi:defcfun ("XGDMatrixFree" xgd-matrix-free) :int
  (handle :pointer))

(cffi:defcfun ("XGDMatrixSaveBinary" xgd-matrix-save-binary) :int
  (handle :pointer)
  (fname :pointer)
  (silent :int))

(cffi:defcfun ("XGDMatrixSetInfoFromInterface" xgd-matrix-set-info-from-interface) :int
  (handle :pointer)
  (field :pointer)
  (data :pointer))

(cffi:defcfun ("XGDMatrixSetFloatInfo" xgd-matrix-set-float-info) :int
  (handle :pointer)
  (field :pointer)
  (array :pointer)
  (len :uint64))

(cffi:defcfun ("XGDMatrixSetUIntInfo" xgd-matrix-set-u-int-info) :int
  (handle :pointer)
  (field :pointer)
  (array :pointer)
  (len :uint64))

(cffi:defcfun ("XGDMatrixSetStrFeatureInfo" xgd-matrix-set-str-feature-info) :int
  (handle :pointer)
  (field :pointer)
  (features :pointer)
  (size :uint64))

(cffi:defcfun ("XGDMatrixGetStrFeatureInfo" xgd-matrix-get-str-feature-info) :int
  (handle :pointer)
  (field :pointer)
  (size :pointer)
  (out-features :pointer))

(cffi:defcfun ("XGDMatrixGetCategories" xgd-matrix-get-categories) :int
  (handle :pointer)
  (config :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixGetCategoriesExportToArrow" xgd-matrix-get-categories-export-to-arrow) :int
  (handle :pointer)
  (config :pointer)
  (out :pointer)
  (export-out :pointer))

(cffi:defcfun ("XGBCategoriesFree" xgb-categories-free) :int
  (handle :pointer))

(cffi:defcfun ("XGDMatrixSetDenseInfo" xgd-matrix-set-dense-info) :int
  (handle :pointer)
  (field :pointer)
  (data :pointer)
  (size :uint64)
  (type :int))

(cffi:defcfun ("XGDMatrixGetInfoRef" xgd-matrix-get-info-ref) :int
  (handle :pointer)
  (field :pointer)
  (out-array :pointer))

(cffi:defcfun ("XGDMatrixGetFloatInfo" xgd-matrix-get-float-info) :int
  (handle :pointer)
  (field :pointer)
  (out-len :pointer)
  (out-dptr :pointer))

(cffi:defcfun ("XGDMatrixGetUIntInfo" xgd-matrix-get-u-int-info) :int
  (handle :pointer)
  (field :pointer)
  (out-len :pointer)
  (out-dptr :pointer))

(cffi:defcfun ("XGDMatrixNumRow" xgd-matrix-num-row) :int
  (handle :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixNumCol" xgd-matrix-num-col) :int
  (handle :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixNumNonMissing" xgd-matrix-num-non-missing) :int
  (handle :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixDataSplitMode" xgd-matrix-data-split-mode) :int
  (handle :pointer)
  (out :pointer))

(cffi:defcfun ("XGDMatrixGetDataAsCSR" xgd-matrix-get-data-as-csr) :int
  (handle :pointer)
  (config :pointer)
  (out-indptr :pointer)
  (out-indices :pointer)
  (out-data :pointer))

(cffi:defcfun ("XGDMatrixGetQuantileCut" xgd-matrix-get-quantile-cut) :int
  (handle :pointer)
  (config :pointer)
  (out-indptr :pointer)
  (out-data :pointer))

(cffi:defcfun ("XGBoosterCreate" xg-booster-create) :int
  (dmats :pointer)
  (len :uint64)
  (out :pointer))

(cffi:defcfun ("XGBoosterFree" xg-booster-free) :int
  (handle :pointer))

(cffi:defcfun ("XGBoosterReset" xg-booster-reset) :int
  (handle :pointer))

(cffi:defcfun ("XGBoosterSlice" xg-booster-slice) :int
  (handle :pointer)
  (begin-layer :int)
  (end-layer :int)
  (step :int)
  (out :pointer))

(cffi:defcfun ("XGBoosterBoostedRounds" xg-booster-boosted-rounds) :int
  (handle :pointer)
  (out :pointer))

(cffi:defcfun ("XGBoosterSetParam" xg-booster-set-param) :int
  (handle :pointer)
  (name :pointer)
  (value :pointer))

(cffi:defcfun ("XGBoosterGetNumFeature" xg-booster-get-num-feature) :int
  (handle :pointer)
  (out :pointer))

(cffi:defcfun ("XGBoosterUpdateOneIter" xg-booster-update-one-iter) :int
  (handle :pointer)
  (iter :int)
  (dtrain :pointer))

(cffi:defcfun ("XGBoosterBoostOneIter" xg-booster-boost-one-iter) :int
  (handle :pointer)
  (dtrain :pointer)
  (grad :pointer)
  (hess :pointer)
  (len :uint64))

(cffi:defcfun ("XGBoosterTrainOneIter" xg-booster-train-one-iter) :int
  (handle :pointer)
  (dtrain :pointer)
  (iter :int)
  (grad :pointer)
  (hess :pointer))

(cffi:defcfun ("XGBoosterEvalOneIter" xg-booster-eval-one-iter) :int
  (handle :pointer)
  (iter :int)
  (dmats :pointer)
  (evnames :pointer)
  (len :uint64)
  (out-result :pointer))

(cffi:defcfun ("XGBoosterPredict" xg-booster-predict) :int
  (handle :pointer)
  (dmat :pointer)
  (option-mask :int)
  (ntree-limit :unsigned-int)
  (training :int)
  (out-len :pointer)
  (out-result :pointer))

(cffi:defcfun ("XGBoosterPredictFromDMatrix" xg-booster-predict-from-d-matrix) :int
  (handle :pointer)
  (dmat :pointer)
  (config :pointer)
  (out-shape :pointer)
  (out-dim :pointer)
  (out-result :pointer))

(cffi:defcfun ("XGBoosterPredictFromDense" xg-booster-predict-from-dense) :int
  (handle :pointer)
  (values :pointer)
  (config :pointer)
  (m :pointer)
  (out-shape :pointer)
  (out-dim :pointer)
  (out-result :pointer))

(cffi:defcfun ("XGBoosterPredictFromColumnar" xg-booster-predict-from-columnar) :int
  (handle :pointer)
  (values :pointer)
  (config :pointer)
  (m :pointer)
  (out-shape :pointer)
  (out-dim :pointer)
  (out-result :pointer))

(cffi:defcfun ("XGBoosterPredictFromCSR" xg-booster-predict-from-csr) :int
  (handle :pointer)
  (indptr :pointer)
  (indices :pointer)
  (values :pointer)
  (ncol :uint64)
  (config :pointer)
  (m :pointer)
  (out-shape :pointer)
  (out-dim :pointer)
  (out-result :pointer))

(cffi:defcfun ("XGBoosterPredictFromCudaArray" xg-booster-predict-from-cuda-array) :int
  (handle :pointer)
  (values :pointer)
  (config :pointer)
  (proxy :pointer)
  (out-shape :pointer)
  (out-dim :pointer)
  (out-result :pointer))

(cffi:defcfun ("XGBoosterPredictFromCudaColumnar" xg-booster-predict-from-cuda-columnar) :int
  (handle :pointer)
  (data :pointer)
  (config :pointer)
  (proxy :pointer)
  (out-shape :pointer)
  (out-dim :pointer)
  (out-result :pointer))

(cffi:defcfun ("XGBoosterLoadModel" xg-booster-load-model) :int
  (handle :pointer)
  (fname :pointer))

(cffi:defcfun ("XGBoosterSaveModel" xg-booster-save-model) :int
  (handle :pointer)
  (fname :pointer))

(cffi:defcfun ("XGBoosterLoadModelFromBuffer" xg-booster-load-model-from-buffer) :int
  (handle :pointer)
  (buf :pointer)
  (len :uint64))

(cffi:defcfun ("XGBoosterSaveModelToBuffer" xg-booster-save-model-to-buffer) :int
  (handle :pointer)
  (config :pointer)
  (out-len :pointer)
  (out-dptr :pointer))

(cffi:defcfun ("XGBoosterSerializeToBuffer" xg-booster-serialize-to-buffer) :int
  (handle :pointer)
  (out-len :pointer)
  (out-dptr :pointer))

(cffi:defcfun ("XGBoosterUnserializeFromBuffer" xg-booster-unserialize-from-buffer) :int
  (handle :pointer)
  (buf :pointer)
  (len :uint64))

(cffi:defcfun ("XGBoosterSaveJsonConfig" xg-booster-save-json-config) :int
  (handle :pointer)
  (out-len :pointer)
  (out-str :pointer))

(cffi:defcfun ("XGBoosterLoadJsonConfig" xg-booster-load-json-config) :int
  (handle :pointer)
  (config :pointer))

(cffi:defcfun ("XGBoosterDumpModel" xg-booster-dump-model) :int
  (handle :pointer)
  (fmap :pointer)
  (with-stats :int)
  (out-len :pointer)
  (out-dump-array :pointer))

(cffi:defcfun ("XGBoosterDumpModelEx" xg-booster-dump-model-ex) :int
  (handle :pointer)
  (fmap :pointer)
  (with-stats :int)
  (format :pointer)
  (out-len :pointer)
  (out-dump-array :pointer))

(cffi:defcfun ("XGBoosterDumpModelWithFeatures" xg-booster-dump-model-with-features) :int
  (handle :pointer)
  (fnum :int)
  (fname :pointer)
  (ftype :pointer)
  (with-stats :int)
  (out-len :pointer)
  (out-models :pointer))

(cffi:defcfun ("XGBoosterDumpModelExWithFeatures" xg-booster-dump-model-ex-with-features) :int
  (handle :pointer)
  (fnum :int)
  (fname :pointer)
  (ftype :pointer)
  (with-stats :int)
  (format :pointer)
  (out-len :pointer)
  (out-models :pointer))

(cffi:defcfun ("XGBoosterGetCategories" xg-booster-get-categories) :int
  (handle :pointer)
  (config :pointer)
  (out :pointer))

(cffi:defcfun ("XGBoosterGetCategoriesExportToArrow" xg-booster-get-categories-export-to-arrow) :int
  (handle :pointer)
  (config :pointer)
  (out :pointer)
  (export-out :pointer))

(cffi:defcfun ("XGBoosterGetAttr" xg-booster-get-attr) :int
  (handle :pointer)
  (key :pointer)
  (out :pointer)
  (success :pointer))

(cffi:defcfun ("XGBoosterSetAttr" xg-booster-set-attr) :int
  (handle :pointer)
  (key :pointer)
  (value :pointer))

(cffi:defcfun ("XGBoosterGetAttrNames" xg-booster-get-attr-names) :int
  (handle :pointer)
  (out-len :pointer)
  (out :pointer))

(cffi:defcfun ("XGBoosterSetStrFeatureInfo" xg-booster-set-str-feature-info) :int
  (handle :pointer)
  (field :pointer)
  (features :pointer)
  (size :uint64))

(cffi:defcfun ("XGBoosterGetStrFeatureInfo" xg-booster-get-str-feature-info) :int
  (handle :pointer)
  (field :pointer)
  (len :pointer)
  (out-features :pointer))

(cffi:defcfun ("XGBoosterFeatureScore" xg-booster-feature-score) :int
  (handle :pointer)
  (config :pointer)
  (out-n-features :pointer)
  (out-features :pointer)
  (out-dim :pointer)
  (out-shape :pointer)
  (out-scores :pointer))

