;;;; c-api.lisp --- CFFI bindings generated from LightGBM/c_api.h.
;;;;
;;;; Generated by tools/regen.lisp. Do not edit by hand.

(uiop:define-package #:cl-gbdt/src/lightgbm/c-api
  (:use #:cl)
  (:import-from #:cffi)
  (:documentation "Raw CFFI bindings for the C API declared in LightGBM/c_api.h.

Every symbol here is generated from the vendored header by tools/regen.lisp.
Nothing outside the backend system should call these directly."))

(in-package #:cl-gbdt/src/lightgbm/c-api)

(cffi:defcfun ("LGBM_GetLastError" lgbm-get-last-error) :pointer)

(cffi:defcfun ("LGBM_DumpParamAliases" lgbm-dump-param-aliases) :int
  (buffer-len :int64)
  (out-len :pointer)
  (out-str :pointer))

(cffi:defcfun ("LGBM_RegisterLogCallback" lgbm-register-log-callback) :int
  (callback :pointer))

(cffi:defcfun ("LGBM_GetSampleCount" lgbm-get-sample-count) :int
  (num-total-row :int32)
  (parameters :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_SampleIndices" lgbm-sample-indices) :int
  (num-total-row :int32)
  (parameters :pointer)
  (out :pointer)
  (out-len :pointer))

(cffi:defcfun ("LGBM_ByteBufferGetAt" lgbm-byte-buffer-get-at) :int
  (handle :pointer)
  (index :int32)
  (out-val :pointer))

(cffi:defcfun ("LGBM_ByteBufferFree" lgbm-byte-buffer-free) :int
  (handle :pointer))

(cffi:defcfun ("LGBM_DatasetCreateFromFile" lgbm-dataset-create-from-file) :int
  (filename :pointer)
  (parameters :pointer)
  (reference :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetCreateFromSampledColumn" lgbm-dataset-create-from-sampled-column) :int
  (sample-data :pointer)
  (sample-indices :pointer)
  (ncol :int32)
  (num-per-col :pointer)
  (num-sample-row :int32)
  (num-local-row :int32)
  (num-dist-row :int64)
  (parameters :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetCreateByReference" lgbm-dataset-create-by-reference) :int
  (reference :pointer)
  (num-total-row :int64)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetInitStreaming" lgbm-dataset-init-streaming) :int
  (dataset :pointer)
  (has-weights :int32)
  (has-init-scores :int32)
  (has-queries :int32)
  (nclasses :int32)
  (nthreads :int32)
  (omp-max-threads :int32))

(cffi:defcfun ("LGBM_DatasetCreateFromSerializedReference" lgbm-dataset-create-from-serialized-reference) :int
  (ref-buffer :pointer)
  (ref-buffer-size :int32)
  (num-row :int64)
  (num-classes :int32)
  (parameters :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetPushRows" lgbm-dataset-push-rows) :int
  (dataset :pointer)
  (data :pointer)
  (data-type :int)
  (nrow :int32)
  (ncol :int32)
  (start-row :int32))

(cffi:defcfun ("LGBM_DatasetPushRowsWithMetadata" lgbm-dataset-push-rows-with-metadata) :int
  (dataset :pointer)
  (data :pointer)
  (data-type :int)
  (nrow :int32)
  (ncol :int32)
  (start-row :int32)
  (label :pointer)
  (weight :pointer)
  (init-score :pointer)
  (query :pointer)
  (tid :int32))

(cffi:defcfun ("LGBM_DatasetPushRowsByCSR" lgbm-dataset-push-rows-by-csr) :int
  (dataset :pointer)
  (indptr :pointer)
  (indptr-type :int)
  (indices :pointer)
  (data :pointer)
  (data-type :int)
  (nindptr :int64)
  (nelem :int64)
  (num-col :int64)
  (start-row :int64))

(cffi:defcfun ("LGBM_DatasetPushRowsByCSRWithMetadata" lgbm-dataset-push-rows-by-csr-with-metadata) :int
  (dataset :pointer)
  (indptr :pointer)
  (indptr-type :int)
  (indices :pointer)
  (data :pointer)
  (data-type :int)
  (nindptr :int64)
  (nelem :int64)
  (start-row :int64)
  (label :pointer)
  (weight :pointer)
  (init-score :pointer)
  (query :pointer)
  (tid :int32))

(cffi:defcfun ("LGBM_DatasetSetWaitForManualFinish" lgbm-dataset-set-wait-for-manual-finish) :int
  (dataset :pointer)
  (wait :int))

(cffi:defcfun ("LGBM_DatasetMarkFinished" lgbm-dataset-mark-finished) :int
  (dataset :pointer))

(cffi:defcfun ("LGBM_DatasetCreateFromCSR" lgbm-dataset-create-from-csr) :int
  (indptr :pointer)
  (indptr-type :int)
  (indices :pointer)
  (data :pointer)
  (data-type :int)
  (nindptr :int64)
  (nelem :int64)
  (num-col :int64)
  (parameters :pointer)
  (reference :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetCreateFromCSRFunc" lgbm-dataset-create-from-csr-func) :int
  (get-row-funptr :pointer)
  (num-rows :int)
  (num-col :int64)
  (parameters :pointer)
  (reference :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetCreateFromCSC" lgbm-dataset-create-from-csc) :int
  (col-ptr :pointer)
  (col-ptr-type :int)
  (indices :pointer)
  (data :pointer)
  (data-type :int)
  (ncol-ptr :int64)
  (nelem :int64)
  (num-row :int64)
  (parameters :pointer)
  (reference :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetCreateFromMat" lgbm-dataset-create-from-mat) :int
  (data :pointer)
  (data-type :int)
  (nrow :int32)
  (ncol :int32)
  (is-row-major :int)
  (parameters :pointer)
  (reference :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetCreateFromMats" lgbm-dataset-create-from-mats) :int
  (nmat :int32)
  (data :pointer)
  (data-type :int)
  (nrow :pointer)
  (ncol :int32)
  (is-row-major :pointer)
  (parameters :pointer)
  (reference :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetCreateFromArrow" lgbm-dataset-create-from-arrow) :int
  (n-chunks :int64)
  (chunks :pointer)
  (schema :pointer)
  (parameters :pointer)
  (reference :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetCreateFromArrowStream" lgbm-dataset-create-from-arrow-stream) :int
  (stream :pointer)
  (parameters :pointer)
  (reference :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetGetSubset" lgbm-dataset-get-subset) :int
  (handle :pointer)
  (used-row-indices :pointer)
  (num-used-row-indices :int32)
  (parameters :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetSetFeatureNames" lgbm-dataset-set-feature-names) :int
  (handle :pointer)
  (feature-names :pointer)
  (num-feature-names :int))

(cffi:defcfun ("LGBM_DatasetGetFeatureNames" lgbm-dataset-get-feature-names) :int
  (handle :pointer)
  (len :int)
  (num-feature-names :pointer)
  (buffer-len :size)
  (out-buffer-len :pointer)
  (feature-names :pointer))

(cffi:defcfun ("LGBM_DatasetFree" lgbm-dataset-free) :int
  (handle :pointer))

(cffi:defcfun ("LGBM_DatasetSaveBinary" lgbm-dataset-save-binary) :int
  (handle :pointer)
  (filename :pointer))

(cffi:defcfun ("LGBM_DatasetSerializeReferenceToBinary" lgbm-dataset-serialize-reference-to-binary) :int
  (handle :pointer)
  (out :pointer)
  (out-len :pointer))

(cffi:defcfun ("LGBM_DatasetDumpText" lgbm-dataset-dump-text) :int
  (handle :pointer)
  (filename :pointer))

(cffi:defcfun ("LGBM_DatasetSetField" lgbm-dataset-set-field) :int
  (handle :pointer)
  (field-name :pointer)
  (field-data :pointer)
  (num-element :int)
  (type :int))

(cffi:defcfun ("LGBM_DatasetSetFieldFromArrow" lgbm-dataset-set-field-from-arrow) :int
  (handle :pointer)
  (field-name :pointer)
  (n-chunks :int64)
  (chunks :pointer)
  (schema :pointer))

(cffi:defcfun ("LGBM_DatasetSetFieldFromArrowStream" lgbm-dataset-set-field-from-arrow-stream) :int
  (handle :pointer)
  (field-name :pointer)
  (stream :pointer))

(cffi:defcfun ("LGBM_DatasetGetField" lgbm-dataset-get-field) :int
  (handle :pointer)
  (field-name :pointer)
  (out-len :pointer)
  (out-ptr :pointer)
  (out-type :pointer))

(cffi:defcfun ("LGBM_DatasetUpdateParamChecking" lgbm-dataset-update-param-checking) :int
  (old-parameters :pointer)
  (new-parameters :pointer))

(cffi:defcfun ("LGBM_DatasetGetNumData" lgbm-dataset-get-num-data) :int
  (handle :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetGetNumFeature" lgbm-dataset-get-num-feature) :int
  (handle :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetGetFeatureNumBin" lgbm-dataset-get-feature-num-bin) :int
  (handle :pointer)
  (feature :int)
  (out :pointer))

(cffi:defcfun ("LGBM_DatasetAddFeaturesFrom" lgbm-dataset-add-features-from) :int
  (target :pointer)
  (source :pointer))

(cffi:defcfun ("LGBM_BoosterGetLinear" lgbm-booster-get-linear) :int
  (handle :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_BoosterCreate" lgbm-booster-create) :int
  (train-data :pointer)
  (parameters :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_BoosterCreateFromModelfile" lgbm-booster-create-from-modelfile) :int
  (filename :pointer)
  (out-num-iterations :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_BoosterLoadModelFromString" lgbm-booster-load-model-from-string) :int
  (model-str :pointer)
  (out-num-iterations :pointer)
  (out :pointer))

(cffi:defcfun ("LGBM_BoosterGetLoadedParam" lgbm-booster-get-loaded-param) :int
  (handle :pointer)
  (buffer-len :int64)
  (out-len :pointer)
  (out-str :pointer))

(cffi:defcfun ("LGBM_BoosterFree" lgbm-booster-free) :int
  (handle :pointer))

(cffi:defcfun ("LGBM_BoosterShuffleModels" lgbm-booster-shuffle-models) :int
  (handle :pointer)
  (start-iter :int)
  (end-iter :int))

(cffi:defcfun ("LGBM_BoosterMerge" lgbm-booster-merge) :int
  (handle :pointer)
  (other-handle :pointer))

(cffi:defcfun ("LGBM_BoosterAddValidData" lgbm-booster-add-valid-data) :int
  (handle :pointer)
  (valid-data :pointer))

(cffi:defcfun ("LGBM_BoosterResetTrainingData" lgbm-booster-reset-training-data) :int
  (handle :pointer)
  (train-data :pointer))

(cffi:defcfun ("LGBM_BoosterResetParameter" lgbm-booster-reset-parameter) :int
  (handle :pointer)
  (parameters :pointer))

(cffi:defcfun ("LGBM_BoosterGetNumClasses" lgbm-booster-get-num-classes) :int
  (handle :pointer)
  (out-len :pointer))

(cffi:defcfun ("LGBM_BoosterUpdateOneIter" lgbm-booster-update-one-iter) :int
  (handle :pointer)
  (produced-empty-tree :pointer))

(cffi:defcfun ("LGBM_BoosterRefit" lgbm-booster-refit) :int
  (handle :pointer)
  (leaf-preds :pointer)
  (nrow :int32)
  (ncol :int32))

(cffi:defcfun ("LGBM_BoosterUpdateOneIterCustom" lgbm-booster-update-one-iter-custom) :int
  (handle :pointer)
  (grad :pointer)
  (hess :pointer)
  (produced-empty-tree :pointer))

(cffi:defcfun ("LGBM_BoosterRollbackOneIter" lgbm-booster-rollback-one-iter) :int
  (handle :pointer))

(cffi:defcfun ("LGBM_BoosterGetCurrentIteration" lgbm-booster-get-current-iteration) :int
  (handle :pointer)
  (out-iteration :pointer))

(cffi:defcfun ("LGBM_BoosterNumModelPerIteration" lgbm-booster-num-model-per-iteration) :int
  (handle :pointer)
  (out-tree-per-iteration :pointer))

(cffi:defcfun ("LGBM_BoosterNumberOfTotalModel" lgbm-booster-number-of-total-model) :int
  (handle :pointer)
  (out-models :pointer))

(cffi:defcfun ("LGBM_BoosterGetEvalCounts" lgbm-booster-get-eval-counts) :int
  (handle :pointer)
  (out-len :pointer))

(cffi:defcfun ("LGBM_BoosterGetEvalNames" lgbm-booster-get-eval-names) :int
  (handle :pointer)
  (len :int)
  (out-len :pointer)
  (buffer-len :size)
  (out-buffer-len :pointer)
  (out-strs :pointer))

(cffi:defcfun ("LGBM_BoosterGetFeatureNames" lgbm-booster-get-feature-names) :int
  (handle :pointer)
  (len :int)
  (out-len :pointer)
  (buffer-len :size)
  (out-buffer-len :pointer)
  (out-strs :pointer))

(cffi:defcfun ("LGBM_BoosterValidateFeatureNames" lgbm-booster-validate-feature-names) :int
  (handle :pointer)
  (data-names :pointer)
  (data-num-features :int))

(cffi:defcfun ("LGBM_BoosterGetNumFeature" lgbm-booster-get-num-feature) :int
  (handle :pointer)
  (out-len :pointer))

(cffi:defcfun ("LGBM_BoosterGetEval" lgbm-booster-get-eval) :int
  (handle :pointer)
  (data-idx :int)
  (out-len :pointer)
  (out-results :pointer))

(cffi:defcfun ("LGBM_BoosterGetNumPredict" lgbm-booster-get-num-predict) :int
  (handle :pointer)
  (data-idx :int)
  (out-len :pointer))

(cffi:defcfun ("LGBM_BoosterGetPredict" lgbm-booster-get-predict) :int
  (handle :pointer)
  (data-idx :int)
  (out-len :pointer)
  (out-result :pointer))

(cffi:defcfun ("LGBM_BoosterPredictForFile" lgbm-booster-predict-for-file) :int
  (handle :pointer)
  (data-filename :pointer)
  (data-has-header :int)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (parameter :pointer)
  (result-filename :pointer))

(cffi:defcfun ("LGBM_BoosterCalcNumPredict" lgbm-booster-calc-num-predict) :int
  (handle :pointer)
  (num-row :int)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (out-len :pointer))

(cffi:defcfun ("LGBM_FastConfigFree" lgbm-fast-config-free) :int
  (fast-config :pointer))

(cffi:defcfun ("LGBM_BoosterPredictForCSR" lgbm-booster-predict-for-csr) :int
  (handle :pointer)
  (indptr :pointer)
  (indptr-type :int)
  (indices :pointer)
  (data :pointer)
  (data-type :int)
  (nindptr :int64)
  (nelem :int64)
  (num-col :int64)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (parameter :pointer)
  (out-len :pointer)
  (out-result :pointer))

(cffi:defcfun ("LGBM_BoosterPredictSparseOutput" lgbm-booster-predict-sparse-output) :int
  (handle :pointer)
  (indptr :pointer)
  (indptr-type :int)
  (indices :pointer)
  (data :pointer)
  (data-type :int)
  (nindptr :int64)
  (nelem :int64)
  (num-col-or-row :int64)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (parameter :pointer)
  (matrix-type :int)
  (out-len :pointer)
  (out-indptr :pointer)
  (out-indices :pointer)
  (out-data :pointer))

(cffi:defcfun ("LGBM_BoosterFreePredictSparse" lgbm-booster-free-predict-sparse) :int
  (indptr :pointer)
  (indices :pointer)
  (data :pointer)
  (indptr-type :int)
  (data-type :int))

(cffi:defcfun ("LGBM_BoosterPredictForCSRSingleRow" lgbm-booster-predict-for-csr-single-row) :int
  (handle :pointer)
  (indptr :pointer)
  (indptr-type :int)
  (indices :pointer)
  (data :pointer)
  (data-type :int)
  (nindptr :int64)
  (nelem :int64)
  (num-col :int64)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (parameter :pointer)
  (out-len :pointer)
  (out-result :pointer))

(cffi:defcfun ("LGBM_BoosterPredictForCSRSingleRowFastInit" lgbm-booster-predict-for-csr-single-row-fast-init) :int
  (handle :pointer)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (data-type :int)
  (num-col :int64)
  (parameter :pointer)
  (out-fast-config :pointer))

(cffi:defcfun ("LGBM_BoosterPredictForCSRSingleRowFast" lgbm-booster-predict-for-csr-single-row-fast) :int
  (fast-config-handle :pointer)
  (indptr :pointer)
  (indptr-type :int)
  (indices :pointer)
  (data :pointer)
  (nindptr :int64)
  (nelem :int64)
  (out-len :pointer)
  (out-result :pointer))

(cffi:defcfun ("LGBM_BoosterPredictForCSC" lgbm-booster-predict-for-csc) :int
  (handle :pointer)
  (col-ptr :pointer)
  (col-ptr-type :int)
  (indices :pointer)
  (data :pointer)
  (data-type :int)
  (ncol-ptr :int64)
  (nelem :int64)
  (num-row :int64)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (parameter :pointer)
  (out-len :pointer)
  (out-result :pointer))

(cffi:defcfun ("LGBM_BoosterPredictForMat" lgbm-booster-predict-for-mat) :int
  (handle :pointer)
  (data :pointer)
  (data-type :int)
  (nrow :int32)
  (ncol :int32)
  (is-row-major :int)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (parameter :pointer)
  (out-len :pointer)
  (out-result :pointer))

(cffi:defcfun ("LGBM_BoosterPredictForMatSingleRow" lgbm-booster-predict-for-mat-single-row) :int
  (handle :pointer)
  (data :pointer)
  (data-type :int)
  (ncol :int)
  (is-row-major :int)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (parameter :pointer)
  (out-len :pointer)
  (out-result :pointer))

(cffi:defcfun ("LGBM_BoosterPredictForMatSingleRowFastInit" lgbm-booster-predict-for-mat-single-row-fast-init) :int
  (handle :pointer)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (data-type :int)
  (ncol :int32)
  (parameter :pointer)
  (out-fast-config :pointer))

(cffi:defcfun ("LGBM_BoosterPredictForMatSingleRowFast" lgbm-booster-predict-for-mat-single-row-fast) :int
  (fast-config-handle :pointer)
  (data :pointer)
  (out-len :pointer)
  (out-result :pointer))

(cffi:defcfun ("LGBM_BoosterPredictForMats" lgbm-booster-predict-for-mats) :int
  (handle :pointer)
  (data :pointer)
  (data-type :int)
  (nrow :int32)
  (ncol :int32)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (parameter :pointer)
  (out-len :pointer)
  (out-result :pointer))

(cffi:defcfun ("LGBM_BoosterPredictForArrow" lgbm-booster-predict-for-arrow) :int
  (handle :pointer)
  (n-chunks :int64)
  (chunks :pointer)
  (schema :pointer)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (parameter :pointer)
  (out-len :pointer)
  (out-result :pointer))

(cffi:defcfun ("LGBM_BoosterPredictForArrowStream" lgbm-booster-predict-for-arrow-stream) :int
  (handle :pointer)
  (stream :pointer)
  (predict-type :int)
  (start-iteration :int)
  (num-iteration :int)
  (parameter :pointer)
  (out-len :pointer)
  (out-result :pointer))

(cffi:defcfun ("LGBM_BoosterSaveModel" lgbm-booster-save-model) :int
  (handle :pointer)
  (start-iteration :int)
  (num-iteration :int)
  (feature-importance-type :int)
  (filename :pointer))

(cffi:defcfun ("LGBM_BoosterSaveModelToString" lgbm-booster-save-model-to-string) :int
  (handle :pointer)
  (start-iteration :int)
  (num-iteration :int)
  (feature-importance-type :int)
  (buffer-len :int64)
  (out-len :pointer)
  (out-str :pointer))

(cffi:defcfun ("LGBM_BoosterDumpModel" lgbm-booster-dump-model) :int
  (handle :pointer)
  (start-iteration :int)
  (num-iteration :int)
  (feature-importance-type :int)
  (buffer-len :int64)
  (out-len :pointer)
  (out-str :pointer))

(cffi:defcfun ("LGBM_BoosterGetLeafValue" lgbm-booster-get-leaf-value) :int
  (handle :pointer)
  (tree-idx :int)
  (leaf-idx :int)
  (out-val :pointer))

(cffi:defcfun ("LGBM_BoosterSetLeafValue" lgbm-booster-set-leaf-value) :int
  (handle :pointer)
  (tree-idx :int)
  (leaf-idx :int)
  (val :double))

(cffi:defcfun ("LGBM_BoosterFeatureImportance" lgbm-booster-feature-importance) :int
  (handle :pointer)
  (num-iteration :int)
  (importance-type :int)
  (out-results :pointer))

(cffi:defcfun ("LGBM_BoosterGetUpperBoundValue" lgbm-booster-get-upper-bound-value) :int
  (handle :pointer)
  (out-results :pointer))

(cffi:defcfun ("LGBM_BoosterGetLowerBoundValue" lgbm-booster-get-lower-bound-value) :int
  (handle :pointer)
  (out-results :pointer))

(cffi:defcfun ("LGBM_NetworkInit" lgbm-network-init) :int
  (machines :pointer)
  (local-listen-port :int)
  (listen-time-out :int)
  (num-machines :int))

(cffi:defcfun ("LGBM_NetworkFree" lgbm-network-free) :int)

(cffi:defcfun ("LGBM_NetworkInitWithFunctions" lgbm-network-init-with-functions) :int
  (num-machines :int)
  (rank :int)
  (reduce-scatter-ext-fun :pointer)
  (allgather-ext-fun :pointer))

(cffi:defcfun ("LGBM_SetMaxThreads" lgbm-set-max-threads) :int
  (num-threads :int))

(cffi:defcfun ("LGBM_GetMaxThreads" lgbm-get-max-threads) :int
  (out :pointer))

(cffi:defcfun ("LGBM_SetLastError" lgbm-set-last-error) :void
  (msg :pointer))

(defconstant +c-api-dtype-float32+ 0)
(defconstant +c-api-dtype-float64+ 1)
(defconstant +c-api-dtype-int32+ 2)
(defconstant +c-api-dtype-int64+ 3)
(defconstant +c-api-feature-importance-gain+ 1)
(defconstant +c-api-feature-importance-split+ 0)
(defconstant +c-api-matrix-type-csc+ 1)
(defconstant +c-api-matrix-type-csr+ 0)
(defconstant +c-api-predict-contrib+ 3)
(defconstant +c-api-predict-leaf-index+ 2)
(defconstant +c-api-predict-normal+ 0)
(defconstant +c-api-predict-raw-score+ 1)
