;;;; emit.lisp --- Emit CFFI definitions from a c2ffi spec file.

(uiop:define-package #:cl-gbdt/src/regen/emit
  (:use #:cl)
  (:import-from #:alexandria)
  (:local-nicknames (#:jzon #:com.inuoe.jzon))
  (:import-from #:cl-gbdt/src/regen/types
                #:cffi-type)
  (:export #:lisp-name
           #:emit-bindings))

(in-package #:cl-gbdt/src/regen/emit)

(defun decamelize (string)
  "Insert dashes at underscore and camelCase boundaries, and downcase."
  (with-output-to-string (out)
    (loop :for i :below (length string)
          :for ch := (char string i)
          :do (cond
                ((char= ch #\_) (write-char #\- out))
                ((and (upper-case-p ch)
                      (plusp i)
                      (or (lower-case-p (char string (1- i)))
                          (digit-char-p (char string (1- i)))
                          (and (< (1+ i) (length string))
                               (lower-case-p (char string (1+ i))))))
                 (write-char #\- out)
                 (write-char (char-downcase ch) out))
                (t (write-char (char-downcase ch) out))))))

(defun collapse-dashes (string)
  "Collapse runs of dashes into one.

`LGBM_GetLastError' decamelizes to `lgbm--get-last-error' because the underscore and
the following case boundary each emit a dash."
  (with-output-to-string (out)
    (loop :with previous-dash := nil
          :for ch :across string
          :do (cond ((char= ch #\-)
                     (unless previous-dash (write-char ch out))
                     (setf previous-dash t))
                    (t (write-char ch out)
                       (setf previous-dash nil))))))

(defun lisp-name (c-name)
  "Return the interned Lisp symbol for the C identifier C-NAME.

`\"LGBM_BoosterCreate\"' becomes `lgbm-booster-create'."
  (intern (string-upcase (string-trim "-" (collapse-dashes (decamelize c-name))))))

(defun spec-entries (path)
  "Read the c2ffi spec at PATH and return its entries as a list."
  (with-open-file (in path :external-format :utf-8)
    (coerce (jzon:parse in) 'list)))

(defun collect-typedefs (entries)
  "Return a hash table mapping typedef names in ENTRIES to their c2ffi types."
  (let ((table (make-hash-table :test #'equal)))
    (dolist (entry entries table)
      (when (equal (gethash "tag" entry) "typedef")
        (setf (gethash (gethash "name" entry) table) (gethash "type" entry))))))

(defun from-header-p (entry header-name)
  "True when ENTRY was declared in HEADER-NAME rather than a system header."
  (search header-name (or (gethash "location" entry) "")))

(defun wanted-p (entry header-name prefixes)
  "True when ENTRY is one of our own declarations, by location and name prefix."
  (let ((name (gethash "name" entry)))
    (and name
         (from-header-p entry header-name)
         (some (lambda (prefix) (alexandria:starts-with-subseq prefix name)) prefixes))))

(defun emit-function (entry typedefs stream)
  "Write a `cffi:defcfun' form for ENTRY to STREAM."
  (let* ((name (gethash "name" entry))
         (parameters (coerce (or (gethash "parameters" entry) #()) 'list))
         (return-type (cffi-type (gethash "return-type" entry) typedefs name)))
    (format stream "~&(cffi:defcfun (\"~A\" ~(~A~)) ~(~S~)"
            name (lisp-name name) return-type)
    (dolist (parameter parameters)
      (format stream "~&  (~(~A~) ~(~S~))"
              (lisp-name (or (gethash "name" parameter) "arg"))
              (cffi-type (gethash "type" parameter) typedefs name)))
    (format stream ")~%~%")))

(defun emit-constant (entry stream)
  "Write a `defconstant' form for ENTRY to STREAM.

Returns true when a form was written. Only integer-valued macros become constants;
a string or floating-point macro is reported to the caller rather than dropped,
because a silently omitted definition is how a binding set ends up quietly
incomplete."
  (let ((value (gethash "value" entry)))
    (when (integerp value)
      (format stream "~&(defconstant +~(~A~)+ ~D)~%" (lisp-name (gethash "name" entry)) value)
      t)))

(defun emit-package-form (header-name package stream)
  "Write the file banner and a `uiop:define-package' form naming PACKAGE to STREAM,
followed by its `in-package' form.

HEADER-NAME is the vendored header the bindings were generated from; it appears
in the banner comment and the package docstring. The package depends on CFFI
through a zero-symbol `:import-from': the file is nothing but `cffi:defcfun' and
`defconstant' forms, so every reference to CFFI is already package-qualified and
none needs importing, but the leaf system still needs the dependency declared."
  (let ((indent "  "))
    (format stream
            ";;;; c-api.lisp --- CFFI bindings generated from ~A.~%~
             ;;;;~%~
             ;;;; Generated by tools/regen.lisp. Do not edit by hand.~%~%~
             (uiop:define-package #:~(~A~)~%~
             ~A(:use #:cl)~%~
             ~A(:import-from #:cffi)~%~
             ~A(:documentation \"Raw CFFI bindings for the C API declared in ~A.~%~
             ~%Every symbol here is generated from the vendored header by ~
             tools/regen.lisp.~%Nothing outside the backend system should call these ~
             directly.\"))~%~%~
             (in-package #:~(~A~))~%~%"
            header-name package indent indent indent header-name package)))

(defun emit-bindings (spec-path header-name package prefixes output)
  "Emit CFFI definitions from SPEC-PATH into OUTPUT.

Only entries declared in HEADER-NAME whose names start with one of PREFIXES are
emitted, into PACKAGE. Functions are written in declaration order; constants are
collected and written afterward sorted by name, because c2ffi does not emit `const'
entries in a stable order between runs. Returns the number of functions and
constants written. Returns a third value: the names of macros that could not become
constants because their values are not integers. Signals `unmapped-type' rather
than skipping any function it cannot map."
  (let* ((entries (spec-entries spec-path))
         (typedefs (collect-typedefs entries))
         (functions 0)
         (constants 0)
         (const-entries '())
         (skipped '()))
    (with-open-file (out output :direction :output :if-exists :supersede
                                :external-format :utf-8)
      (emit-package-form header-name package out)
      (dolist (entry entries)
        (when (wanted-p entry header-name prefixes)
          (cond ((equal (gethash "tag" entry) "function")
                 (emit-function entry typedefs out)
                 (incf functions))
                ((equal (gethash "tag" entry) "const")
                 (push entry const-entries)))))
      ;; The sort key is total: C macro names are unique within a translation unit, so no
      ;; two entries tie and the result does not depend on `sort' being stable. `stable-sort'
      ;; would not help if they did tie -- it would preserve c2ffi's order, which is the
      ;; non-determinism this sort exists to remove. Uniqueness itself rests on c2ffi
      ;; emitting one `const' entry per surviving `#define' -- a `#undef'-and-redefine pair
      ;; would break it, and if that ever happened, the twice-run byte-identity check
      ;; (`committed-bindings-match-their-committed-spec') would fail loudly, which is
      ;; the right failure.
      (dolist (entry (sort (nreverse const-entries) #'string<
                            :key (lambda (entry) (gethash "name" entry))))
        (if (emit-constant entry out)
            (incf constants)
            (push (gethash "name" entry) skipped))))
    (values functions constants (nreverse skipped))))
